/**
 * Read a "exchange.json" file and output the stock history for each
 * stock into a "stock_symbol".json file.
 * 
 * The stock symbols file.
 * 
 * E.g.
 * 
 * casperjs getStockHistory.js KLSE.json
 * 
 */
"use strict";

String.prototype.format = String.prototype.f = function() {
    var s = this,
        i = arguments.length;

    while (i--) {
        s = s.replace(new RegExp('\\{' + i + '\\}', 'gm'), arguments[i]);
    }
    return s;
};

// http://www.google.com/finance/historical?q=KLSE%3AYTLPOWR&startdate=Mar%2012%2C%202015&enddate=Mar%2011%2C%202017&ei=Vy3EWJGzCZmW0QTqh6HAAg&output=csv

var GOOGLE_FINANCE_URL_GET_STOCK_HISTORY = 'http://www.google.com/finance/historical?q={0}%3A{1}&ei=zsb0V4H5K5LQuATWx7_oDQ&output=csv';

var system = require('system'),
    casper = require('casper').create(),
    timestamp,
    historicalDataUrl;

var fs = require('fs');

//casper.echo("Casper CLI passed args:");
//require("utils").dump(casper.cli.args);

//casper.echo("Casper CLI passed options:");
//require("utils").dump(casper.cli.options);


var stockSymbolFileName = '';
if (casper.cli.args.length === 0) {
    console.log('Pass in the name of the stock symbol file generated by getStockSymbols.js');
    casper.exit(1);
} else {
    timestamp = Date.now();
    stockSymbolFileName = casper.cli.args[0];
    var exchangeName = stockSymbolFileName.split('.')[0];
    console.log('Getting stock symbols for [' + exchangeName + ']');

    // Read the file
    try {
        var content = fs.read(stockSymbolFileName);
        var stocks = JSON.parse(content);

        // Create a folder named after the exchange name
        if (!fs.exists(exchangeName) || (fs.exists(exchangeName) && !fs.isDirectory(exchangeName))) {
            if (fs.makeDirectory(exchangeName)) {
                console.log('Created the folder [' + exchangeName + ']');
            } else {
                console.log('Unable to create folder [' + exchangeName + ']');
            }
        } else {
            console.log('Folder [' + exchangeName + '] already exists');
        }

        if (Array.isArray(stocks)) {
            casper.start('http://www.google.com/finance/', function() {
                for (var counter = 0; counter < stocks.length; counter++) {
                    var stock = stocks[counter];
                    // Get historical price for each stock
                    historicalDataUrl = GOOGLE_FINANCE_URL_GET_STOCK_HISTORY;
                    historicalDataUrl = historicalDataUrl.format(exchangeName, encodeURIComponent(stock.symbol));
                    console.log('Retrieving historical data for [' + stock.company + ']');
                    //casper.echo(historicalDataUrl);
                    this.download(historicalDataUrl, exchangeName + fs.separator + stock.symbol + '.csv');
                }
                timestamp = Date.now() - timestamp;
                console.log('Total time: ' + (timestamp / 1000) + ' seconds');
                casper.exit();
            });
            casper.run();
        } else {
            casper.exit(1);
        }
    } catch (e) {
        console.log('Unable to get stock history.');
        console.log(e.message);
        casper.exit(1);
    }
}